analysis:
  max_file_size_mb: 200
  max_string_file_size_mb: 50
  min_string_length: 5
  string_limit_per_file: 2000
  jobs: 1
  keep_extracted: true
paths:
  high_risk:
    - /Library/MobileSubstrate/DynamicLibraries
    - /var/jb/Library/MobileSubstrate/DynamicLibraries
    - /Library/PreferenceBundles
    - /var/jb/Library/PreferenceBundles
    - /Library/PreferenceLoader/Preferences
    - /var/jb/Library/PreferenceLoader/Preferences
    - /Applications
    - /var/jb/Applications